from dominio.excepciones.limite_de_prestamos_excedido import LimiteDePrestamosExcedido
from dominio.excepciones.multa_pendiente import MultaPendiente
from dominio.excepciones.estudiante_no_encontrado import EstudianteNoEncontrado
from dominio.excepciones.dispositivo_no_encontrado import DispositivoNoEncontrado
from dominio.excepciones.dispositivo_no_disponible import DispositivoNoDisponible
from dominio.excepciones.prestamo_no_encontrado import PrestamoNoEncontrado